image: docker:latest

stages:
- build
- test
- docker
- deploy

build:
  image: maven:3-openjdk-17
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main
    - develop

test:
  image: maven:3-openjdk-17
  stage: test
  script:
    - mvn test
  only:
    - main
    - develop

docker:
  stage: docker

  services:
  - docker:dind

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
  dependencies:
  - test
  
  script:
    - docker build -t "$CI_REGISTRY_USER/api-admin-pipe:latest" .
    - docker push "$CI_REGISTRY_USER/api-admin-pipe:latest"
    
  only:
    - main
    - develop